---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

local-docker:
  socket: /var/run/docker-proxy/docker.sock

local-podman:
  socket: /var/run/podman-proxy/docker.sock

