---
services:
  # https://github.com/linuxserver/docker-socket-proxy/
  dockerproxy:
    image: ${SOCKET_PROXY_IMAGE:?socket proxy}:${SOCKET_PROXY_TAG:-latest}
    # ports:
    #   - 127.0.0.1:2375:2375, # used by homepage auto-discovery (no need to expose to host)
    environment:
      CONTAINERS: 1 # Allow access to viewing containers
      IMAGES: 1 # Allow access to viewing images
      POST: 0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: ${RESTART}

  # https://github.com/gethomepage/homepage
  homepage:
    image: ${HOMEPAGE_IMAGE:?homepage image}:${HOMEPAGE_TAG:-latest}
    # ports:
    #   - 127.0.0.1:3000:3000, # exposed though reverse proxy
    volumes:
      - ./homepage/config:/app/config
    environment:
      PUID: ${PUID:?user id} # check `id` on host
      PGID: ${PGID:?group id} # check `id` on host
      TZ: ${TZ:?timezone}
      HOMEPAGE_ALLOWED_HOSTS: "*" # gethomepage.dev/installation/#homepage_allowed_hosts
    restart: ${RESTART}
