---
services:
  # https://github.com/11notes/docker-socket-proxy
  dockerproxy:
    image: ${SOCKET_PROXY_IMAGE:?socket proxy image required}:${SOCKET_PROXY_TAG:-latest}
    read_only: true
    # Note: When using Docker Desktop on macOS, the mounted files are owned by root:root, so you need to run the container as root :(
    # user: "${PUID:?user id required}:${PGID:?group id required}" # make sure to use the same PUID/PGID as the owner of your docker socket!
    environment:
      TZ: ${TZ:?timezone required}
      SOCKET_PROXY_DOCKER_SOCKET: /run/docker.sock # path to the actual docker socket
      SOCKET_PROXY_VOLUME: /run/docker-proxy # path to the docker volume used to expose the prox socket
      SOCKET_PROXY_UID: "${PUID:?user id required}" # the UID used to run the proxy parts
      SOCKET_PROXY_GID: "${PGID:?group id required}" # the GID used to run the proxy parts
    volumes:
      - ~/.docker/run/docker.sock:/run/docker.sock:ro # mount host docker socket, the :ro does not mean read-only for the socket, just for the actual file
      - docker-socket-proxy:/run/docker-proxy # this socket is run as defined by env variables
    restart: ${RESTART}

  # https://github.com/11notes/docker-socket-proxy
  podmanproxy:
    image: ${SOCKET_PROXY_IMAGE:?socket proxy image required}:${SOCKET_PROXY_TAG:-latest}
    read_only: true
    # Note: When using Docker Desktop on macOS, the mounted files are owned by root:root, so you need to run the container as root :(
    # user: "${PUID:?user id required}:${PGID:?group id required}" # make sure to use the same PUID/PGID as the owner of your docker socket!
    profiles:
      - podman-proxy
    environment:
      TZ: ${TZ:?timezone required}
      SOCKET_PROXY_DOCKER_SOCKET: /run/docker.sock # path to the actual docker socket
      SOCKET_PROXY_VOLUME: /run/podman-proxy # path to the docker volume used to expose the prox socket
      SOCKET_PROXY_UID: "${PUID:?user id required}" # the UID used to run the proxy parts
      SOCKET_PROXY_GID: "${PGID:?group id required}" # the GID used to run the proxy parts
    volumes:
      - ~/.local/share/containers/podman/machine/podman.sock:/run/docker.sock:ro # mount host docker socket, the :ro does not mean read-only for the socket, just for the actual file
      - podman-socket-proxy:/run/podman-proxy # this socket is run as defined by env variables
    restart: ${RESTART}

  # https://github.com/gethomepage/homepage
  homepage:
    image: ${HOMEPAGE_IMAGE:?homepage image required}:${HOMEPAGE_TAG:-latest}
    # ports:
    #   - 127.0.0.1:3000:3000, # exposed though reverse proxy
    volumes:
      - ./homepage/config:/app/config
      - docker-socket-proxy:/var/run/docker-proxy # mount the docker socket proxy
      - podman-socket-proxy:/var/run/podman-proxy # mount the podman socket proxy
    environment:
      PUID: ${PUID:?user id required} # check `id` on host
      PGID: ${PGID:?group id required} # check `id` on host
      TZ: ${TZ:?timezone required}
      HOMEPAGE_ALLOWED_HOSTS: "*" # gethomepage.dev/installation/#homepage_allowed_hosts
    restart: ${RESTART}

volumes:
  docker-socket-proxy:
  podman-socket-proxy:
