---
services:
  # https://docs.linuxserver.io/images/docker-nginx/
  nginx:
    image: ${IMAGE:?nginx image required}:${TAG:-latest}
    environment:
      PUID: ${PUID:?user id required}
      PGID: ${PGID:?group id required}
      TZ: ${TZ:?timezone required}
      # https://github.com/linuxserver/docker-mods/tree/nginx-proxy-confs
      # https://github.com/linuxserver/docker-mods/tree/universal-package-install
      DOCKER_MODS: linuxserver/mods:nginx-proxy-confs|linuxserver/mods:universal-package-install
    volumes:
      - ./nginx/config:/config
      - ./service-certs:/config/service-certs:ro
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    restart: ${RESTART}
