---
name: mac-pro-composes

services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    environment:
      PUID: 501  # check `id` on host
      PGID: 20   # check `id` on host
      TZ: Europe/Prague # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      # https://github.com/linuxserver/docker-mods/tree/nginx-proxy-confs
      # https://github.com/linuxserver/docker-mods/tree/universal-package-install
      DOCKER_MODS: linuxserver/mods:nginx-proxy-confs|linuxserver/mods:universal-package-install
    volumes:
      - ./nginx/config:/config
      - ./service-certs:/config/service-certs:ro
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    restart: unless-stopped

networks:
  default:
    external: true
    name: mac-pro-composes  # shared network
