---
services:
  # https://docs.linuxserver.io/images/docker-firefox/
  firefox:
    image: ${FIREFOX_IMAGE:?firefox image required}:${FIREFOX_TAG:-latest}
    profiles:
      - firefox
    security_opt: [
        seccomp:unconfined, # better compatibility with some hosts
      ]
    environment:
      # https://github.com/linuxserver/docker-firefox#optional-environment-variables
      PUID: ${PUID:?user id required}
      PGID: ${PGID:?group id required}
      TZ: ${TZ:?timezone required}
      TITLE: ${TITLE}
      NO_DECOR: ${NO_DECOR}
      FM_HOME: ${FM_HOME}
      START_DOCKER: ${START_DOCKER}
      FILE__CUSTOM_USER: /run/secrets/firefox-basic-auth-user
      FILE__PASSWORD: /run/secrets/firefox-basic-auth-password
      DOCKER_MODS: linuxserver/mods:universal-cron # enables cron jobs from ./firefox/crontabs
    volumes:
      - ./firefox/config:/config
      - ./firefox/crontabs:/config/crontabs:ro
      - ./firefox/scripts:/config/scripts:ro
      # keep firefox profile data out of host filesystem
      - mozilla-data:/config/.mozilla # firefox profile data
      - mozilla-cache:/config/.cache/mozilla/ # firefox cache
    secrets:
      - firefox-basic-auth-user
      - firefox-basic-auth-password
    ports:
      - 127.0.0.1:${HOST_PORT:-3001}:3001 # https firefox desktop GUI (direct access enabled)
    shm_size: ${SHM_SIZE:-1gb}
    restart: ${RESTART}
    labels:
      homepage.group: Utils
      homepage.name: ${TITLE}
      homepage.icon: firefox.svg # https://gethomepage.dev/configs/services/#icons
      # homepage.href: "https://firefox.localhost/" # through nginx proxy
      homepage.href: "https://127.0.0.1:${HOST_PORT:-3001}/" # direct access
      homepage.description: "Firefox browser"

volumes:
  mozilla-data:
  mozilla-cache:

secrets:
  firefox-basic-auth-user:
    file: ${FIREFOX_SECRETS_BASE_DIR}/basic-auth-user
  firefox-basic-auth-password:
    file: ${FIREFOX_SECRETS_BASE_DIR}/basic-auth-password
