---
x-refs:
  shared-envs: &shared-envs
    PUID: &puid ${PUID:?user id required}
    PGID: &pgid ${PGID:?group id required}
    TZ: &tz ${TZ:?timezone required}

services:
  # https://docs.linuxserver.io/images/docker-obsidian/
  obsidian:
    image: ${OBSIDIAN_IMAGE:?obsidian image required}:${OBSIDIAN_TAG:-latest}
    profiles:
      - obsidian
    security_opt: [
        seccomp:unconfined, # better compatibility with some hosts
      ]
    environment:
      <<: *shared-envs
      # https://github.com/linuxserver/docker-obsidian#optional-environment-variables
      TITLE: ${TITLE}
      FM_HOME: ${FM_HOME}
      START_DOCKER: ${START_DOCKER}
      FILE__CUSTOM_USER: /run/secrets/obsidian-basic-auth-user
      FILE__PASSWORD: /run/secrets/obsidian-basic-auth-password
    volumes:
      - ./obsidian/config:/config
      - &datamount syncthing-data:/config/data
      # use with put_obsidian.zsh script to copy any files from host to obsidian vault
      - ./obsidian/to-obsidian:/media/to-config-data
    secrets:
      - obsidian-basic-auth-user
      - obsidian-basic-auth-password
    ports:
      - 127.0.0.1:${HOST_PORT:-3001}:3001 # https obsidian desktop GUI
    shm_size: ${SHM_SIZE:-1gb}
    restart: &restart ${RESTART}
    labels:
      one.dify.obsidian.putscript: "true" # explicit label which helps put_obsidian.zsh script find this container
      homepage.group: Tools
      homepage.name: Obsidian
      homepage.icon: obsidian.svg # https://gethomepage.dev/configs/services/#icons
      homepage.href: "https://localhost:${HOST_PORT:-3001}/"
      homepage.description: "Personal knowledge data lake"
    depends_on:
      - syncthing

  # https://docs.linuxserver.io/images/docker-syncthing/
  syncthing:
    image: ${SYNCTHING_IMAGE:?syncthing image required}:${SYNCTHING_TAG:-latest}
    profiles:
      - obsidian
      - syncthing
    environment:
      <<: *shared-envs
    labels:
      homepage.group: Utils
      homepage.name: Syncthing
      homepage.icon: syncthing.svg # https://gethomepage.dev/configs/services/#icons
      homepage.href: "https://syncthing.localhost/"
      homepage.description: "Sync files between devices"
    volumes:
      - ./syncthing/config:/config
      - *datamount
    # ports:
    #   - 127.0.0.1:8384:8384 # http syncthing GUI (exposed through reverse proxy)
    #   # disable discovery ports, this device won't be reachable directly
    #   - 22000:22000/tcp # TCP based sync protocol traffic
    #   - 22000:22000/udp # QUIC based sync protocol traffic
    #   - 21027:21027/udp # discovery broadcasts on IPv4 and multicasts on IPv6
    restart: *restart

volumes:
  syncthing-data:

secrets:
  obsidian-basic-auth-user:
    file: ${OBSIDIAN_SECRETS_BASE_DIR}/basic-auth-user
  obsidian-basic-auth-password:
    file: ${OBSIDIAN_SECRETS_BASE_DIR}/basic-auth-password
