# todo: update
FROM httpd:latest

WORKDIR /

RUN apt update && apt install git -y
RUN git clone https://github.com/httpcats/http.cat.git && \
    cp /http.cat/public/images/* /usr/local/apache2/htdocs/ && \
    rm -rf /http.cat/
